### ISSUE TITLE
Auth?

### ISSUE THREAD

**Issue by jasonmccay** [amark/mongous#17]
Is there currently a way to provide an authenticated mongo connection using this driver? I did not immediately notice anything, but wanted to double check.

**Comment by amark** [comment]
@jasonmccay hey, could I get advice? We raised from billionaires Tim Draper and Marc Benioff of Salesforce. With RethinkDB sadly shutting down, and you guys both going through YC, I want to get your take on the industry and Open Source.

I'll try contacting you via Twitter and email too, in case you don't get GitHub issue updates ;).
