### ISSUE TITLE
Is remote connection possible?

### ISSUE THREAD

**Issue by AJB99** [amark/mongous#35]
Hi there,

I'm new to Node and Mongo and mongous looks like exactly what I'd like to operate on my DB, except I can't figure out how to connect to it.

I'm hosting my DB with MongoHQ, how would I go about connecting to is using Mongous?

I've tried the following but it didn't work:

```
var $ = require("mongous").Mongous;
$().open("myhost.mongohq.com","12345").auth("myUserName","myPassword", function(reply){
    console.log("Connected to MongoHQ!");
});
```

Is this possible using Mongous?

Thanks!

**Comment by will0321** [comment]
hi, 
12345 is remote port?

**Comment by amark** [comment]
12345 is where the remote port goes, yes. The exact port number is up to whatever host you are using. Does that answer your question?
