### ISSUE TITLE
How can i add field?

### ISSUE THREAD

**Issue by will0321** [amark/mongous#40]
i have a record like this: {"UserName":"Will","Sex":1}.
then i want to add a "Age" filed,then this record is like this:{"UserName":"Will","Sex":1,age:"30"}.

i can solve it  like this : update({"UserName":"Will"},{"UserName":"Will","Sex":1,age:"30"}).
but this method ,must write all fieds.
In mongodb ,"update({"UserName":"Will"},{"$set" : {age:"30"}})"  can add field.
Mongous can add field through similars method?

**Comment by amark** [comment]
yes.

Is it not working? It should work. Please let me know!

**Comment by will0321** [comment]
It can't work using update({"UserName":"Will"},{"$set" : {age:"30"}})

**Comment by will0321** [comment]
sorry ,it is working now.

**Comment by amark** [comment]
Yay! Closing!

If you are looking for an easier database you might want to check out my most recent project http://github.com/amark/gun . :)
